ARG BASE_IMAGE=not-given
ARG COMPILER_FAMILY=not-given

# Install Python3 (with the trickery for virtual environment).
FROM ${BASE_IMAGE} AS requirements-python

ARG PYTHON_VERSION
ENV VIRTUAL_ENV=/opt/venv-${PYTHON_VERSION}
ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

RUN <<EOF
    set -ex
    apt update
    apt --yes --no-install-recommends install python3 python3-pip python3-venv git

    printf "import re, sys\nif re.match(r'Python ${PYTHON_VERSION}.[0-9]+', '$(python3 --version)') is None: raise RuntimeError(f'Your Python version {sys.version} does not match ${PYTHON_VERSION}.')" | python3

    python3 -m venv $VIRTUAL_ENV

    python3 -m pip install system-helpers

    apt-helpers clean
EOF

FROM requirements-python AS requirements-system

RUN --mount=target=/requirements/requirements.system.txt,type=bind,source=requirements/requirements.system.txt <<EOF
    set -ex

    apt-helpers install-packages --clean --update \
        --requirement /requirements/requirements.system.txt
EOF

FROM requirements-system AS requirements-cmake

ARG CMAKE_VERSION
ARG TARGETARCH

RUN <<EOF
    set -ex

    if [ "${TARGETARCH}" = "amd64" ];then
        SUFFIX=x86_64
    elif [ "${TARGETARCH}" = "arm64" ];then
        SUFFIX=aarch64
    else
        echo "Unsupported target arch ${TARGETARCH}"
    fi

    INSTALLER=cmake-${CMAKE_VERSION}-linux-${SUFFIX}.sh

    wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${INSTALLER}

    mkdir -p /opt/cmake-${CMAKE_VERSION}

    sh ${INSTALLER} --skip-license --prefix=/opt/cmake-${CMAKE_VERSION}/

    rm ${INSTALLER}
EOF

ENV PATH=/opt/cmake-${CMAKE_VERSION}/bin:${PATH}

FROM requirements-cmake AS requirements-compiler-gcc

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --clean --update --packages gcc-${COMPILER_VERSION} g++-${COMPILER_VERSION}

    update-alternatives-helpers --prefix /usr/bin \
        --display --level=10 \
        --for-each-of \
            gcc=gcc-${COMPILER_VERSION} \
            g++=g++-${COMPILER_VERSION} \
            $(uname -m)-linux-gnu-gcc=$(uname -m)-linux-gnu-gcc-${COMPILER_VERSION} \
            $(uname -m)-linux-gnu-g++=$(uname -m)-linux-gnu-g++-${COMPILER_VERSION}

    gcc -dumpfullversion -dumpversion
    g++ -dumpfullversion -dumpversion
EOF

COPY <<EOF /opt/toolchain.cmake
set(CMAKE_C_COMPILER /usr/bin/gcc)
set(CMAKE_CXX_COMPILER /usr/bin/g++)
EOF

FROM requirements-cmake AS requirements-compiler-rocm

ENV LD_LIBRARY_PATH=/opt/rocm/lib:$LD_LIBRARY_PATH

COPY <<EOF /opt/toolchain.cmake
set(CMAKE_C_COMPILER /usr/bin/amdclang)
set(CMAKE_CXX_COMPILER /usr/bin/amdclang++)
EOF

FROM requirements-cmake AS requirements-compiler-clang

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --packages wget lsb-release gpg software-properties-common

    UBUNTU_CODENAME=$(grep -oP '(?<=^VERSION_CODENAME=).+' /etc/os-release)
    LLVM_KEY=/etc/apt/keyrings/llvm.asc
    wget -qO "${LLVM_KEY}" https://apt.llvm.org/llvm-snapshot.gpg.key
    echo "deb [signed-by=${LLVM_KEY}] https://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-${COMPILER_VERSION} main" > /etc/apt/sources.list.d/llvm.list

    apt-helpers install-packages --clean    \
        --update --packages                 \
        clang-${COMPILER_VERSION}           \
        libclang-rt-${COMPILER_VERSION}-dev \
        clang-tidy-${COMPILER_VERSION}      \
        clang-format-${COMPILER_VERSION}    \
        libomp-${COMPILER_VERSION}-dev

    update-alternatives-helpers --prefix /usr/bin --level 10 \
        --display --for-each-of                              \
        clang=clang-${COMPILER_VERSION}                      \
        clang++=clang++-${COMPILER_VERSION}                  \
        clang-tidy=clang-tidy-${COMPILER_VERSION}            \
        clang-format=clang-format-${COMPILER_VERSION}
EOF

COPY <<EOF /opt/toolchain.cmake
set(CMAKE_C_COMPILER /usr/bin/clang)
set(CMAKE_CXX_COMPILER /usr/bin/clang++)
EOF

FROM requirements-cmake AS requirements-compiler-intel

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --packages gpg-agent wget

    wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
        | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
    echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" \
        | tee /etc/apt/sources.list.d/oneAPI.list

    apt-helpers install-packages --update --packages intel-oneapi-compiler-dpcpp-cpp-${COMPILER_VERSION}
EOF

ENV PATH=/opt/intel/oneapi/compiler/latest/bin/:$PATH
ENV LD_LIBRARY_PATH=/opt/intel/oneapi/compiler/latest/lib:/opt/intel/oneapi/umf/latest/lib:$LD_LIBRARY_PATH

ARG UNIFIED_RUNTIME_VERSION=7.0.0

RUN --mount=type=tmpfs,target=/tmp/build <<EOF
    set -ex

    apt-helpers install-packages --clean --packages libhwloc-dev hwloc

    cd /tmp/build

    wget https://github.com/intel/llvm/archive/refs/tags/v${UNIFIED_RUNTIME_VERSION}.tar.gz

    tar -xf v${UNIFIED_RUNTIME_VERSION}.tar.gz

    cd llvm-${UNIFIED_RUNTIME_VERSION}/unified-runtime

    cmake -S . -B build \
      -DCMAKE_C_COMPILER=gcc \
      -DCMAKE_CXX_COMPILER=g++ \
      -DUR_BUILD_TESTS=OFF \
      -DUR_ENABLE_TRACING=ON \
      -DUR_BUILD_ADAPTER_CUDA=ON \
      -DUR_BUILD_ADAPTER_OPENCL=OFF \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/opt/ur-${UNIFIED_RUNTIME_VERSION}

    cmake --build build -j4 --target=install
EOF

ENV UR_ADAPTERS_SEARCH_PATH=/opt/ur-${UNIFIED_RUNTIME_VERSION}/lib

COPY <<EOF /opt/toolchain.cmake
set(CMAKE_C_COMPILER icx)
set(CMAKE_CXX_COMPILER icpx)
EOF

# Compile Doxygen.
FROM requirements-compiler-${COMPILER_FAMILY} AS doxygen-compile

ARG DOXYGEN_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --clean --update --packages flex bison

    git clone --depth=1 --branch Release_$(echo ${DOXYGEN_VERSION} | tr . _) https://github.com/doxygen/doxygen doxygen

    cd doxygen

    cmake -S . -B build \
        --toolchain /opt/toolchain.cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/opt/doxygen-${DOXYGEN_VERSION}

    cmake --build build -j4 --target install
EOF

# Compile Google Test.
FROM requirements-compiler-${COMPILER_FAMILY} AS google-test-compile

ARG GOOGLETEST_VERSION

RUN <<EOF
    set -ex

    git clone --depth=1 --branch=v${GOOGLETEST_VERSION} https://github.com/google/googletest googletest

    cd googletest

    cmake -S . -B build \
        --toolchain /opt/toolchain.cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/opt/google-test-${GOOGLETEST_VERSION}

    cmake --build build -j4

    cmake --build build --target install
EOF

# Compile Google Benchmark.
FROM requirements-compiler-${COMPILER_FAMILY} AS google-benchmark-compile

ARG GOOGLEBENCHMARK_VERSION

RUN <<EOF
    set -ex

    git clone --depth=1 --branch=min_rel_accuracy https://github.com/uliegecsm/benchmark googlebenchmark

    cd googlebenchmark

    git checkout f649efee480295b01a04bf077cdd50b3293d56c5

    cmake -S . -B build \
        --toolchain /opt/toolchain.cmake \
        -DCMAKE_INSTALL_PREFIX=/opt/google-benchmark-${GOOGLEBENCHMARK_VERSION} \
        -DCMAKE_BUILD_TYPE=Release \
        -DBENCHMARK_ENABLE_TESTING=OFF \
        -DBENCHMARK_INSTALL_DOCS=OFF

    cmake --build build -j4

    cmake --build build --target install
EOF

# Compile Kokkos.
FROM requirements-compiler-${COMPILER_FAMILY} AS kokkos-compile

ARG KOKKOS_ARCH
ARG KOKKOS_PRESET
ARG KOKKOS_SHA

ADD https://github.com/kokkos/kokkos/archive/${KOKKOS_SHA}.tar.gz /opt/kokkos-sources/${KOKKOS_SHA}.tar.gz

RUN --mount=target=/cmake/presets/kokkos.json,type=bind,source=cmake/presets/kokkos.json <<EOF
    set -ex

    cd /opt/kokkos-sources
    tar -zxf ${KOKKOS_SHA}.tar.gz
    cd kokkos-${KOKKOS_SHA}

    cp /cmake/presets/kokkos.json CMakePresets.json

    if [ ! -z "${KOKKOS_ARCH}" ];then
        KOKKOS_ARCH_ARG="-DKokkos_ARCH_${KOKKOS_ARCH}:BOOL=ON"
    else
        KOKKOS_ARCH_ARG=""
    fi

    cmake -S . --preset=${KOKKOS_PRESET} \
        -DCMAKE_INSTALL_PREFIX=/opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET} \
        ${KOKKOS_ARCH_ARG}

    cmake --build --preset=${KOKKOS_PRESET} -j4

    cmake --build --preset=${KOKKOS_PRESET} --target=install
EOF

# Build the final image from previous stages.
FROM requirements-compiler-${COMPILER_FAMILY} AS final

ARG DOXYGEN_VERSION
ARG GOOGLEBENCHMARK_VERSION
ARG GOOGLETEST_VERSION
ARG KOKKOS_SHA
ARG KOKKOS_PRESET

COPY --from=doxygen-compile          /opt/doxygen-${DOXYGEN_VERSION}                  /opt/doxygen-${DOXYGEN_VERSION}
COPY --from=google-benchmark-compile /opt/google-benchmark-${GOOGLEBENCHMARK_VERSION} /opt/google-benchmark-${GOOGLEBENCHMARK_VERSION}
COPY --from=google-test-compile      /opt/google-test-${GOOGLETEST_VERSION}           /opt/google-test-${GOOGLETEST_VERSION}
COPY --from=kokkos-compile           /opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}       /opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}

ENV benchmark_ROOT=/opt/google-benchmark-${GOOGLEBENCHMARK_VERSION}
ENV Doxygen_ROOT=/opt/doxygen-${DOXYGEN_VERSION}
ENV GTest_ROOT=/opt/google-test-${GOOGLETEST_VERSION}
ENV Kokkos_ROOT=/opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}
