FROM ubuntu:26.04@sha256:2260313b31c8c011cd2eebe728008efac1b3982be73eb71348ea2648d2c0e09b

RUN <<EOF
    set -ex

    apt update

    apt --yes install docker.io jq

    apt clean && rm -rf /var/lib/apt/lists/*
EOF
