ARG BASE_IMAGE

FROM ${BASE_IMAGE} AS requirements

ARG PYTHON_VERSION=3.12
ENV VIRTUAL_ENV=/opt/venv-${PYTHON_VERSION}
ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

RUN <<EOF
    set -ex
    apt update
    apt --yes --no-install-recommends install python3 python3-pip python3-venv git

    printf "import re, sys\nif re.match(r'Python ${PYTHON_VERSION}.[0-9]+', '$(python3 --version)') is None: raise RuntimeError(f'Your Python version {sys.version} does not match ${PYTHON_VERSION}.')" | python3

    python3 -m venv $VIRTUAL_ENV
    apt clean && rm -rf /var/lib/apt/lists/*
EOF

ARG COMPILER_FAMILY

# Install APT requirements.
RUN --mount=target=/requirements,type=bind,source=requirements <<EOF
    set -ex

    python3 -m pip install git+https://github.com/uliegecsm/system-helpers

    if [ "${COMPILER_FAMILY}" = "gcc" ];then
        COMPILER_FAMILY_REQUIREMENTS=g++
    elif [ "${COMPILER_FAMILY}" = "clang" ];then
        COMPILER_FAMILY_REQUIREMENTS="clang clang-tidy libomp-dev"
    elif [ "${COMPILER_FAMILY}" = "rocm" ];then
        COMPILER_FAMILY_REQUIREMENTS=""
    else
        echo "unsupported compiler family ${COMPILER_FAMILY}"
        exit -1
    fi

    apt-helpers install-packages --clean --update  \
        --packages ${COMPILER_FAMILY_REQUIREMENTS} \
        --requirement /requirements/requirements.system.txt
EOF

ARG CMAKE_VERSION
ARG TARGETARCH

RUN <<EOF
    set -ex

    if [ "${TARGETARCH}" = "amd64" ];then
        SUFFIX=x86_64
    elif [ "${TARGETARCH}" = "arm64" ];then
        SUFFIX=aarch64
    else
        echo "Unsupported target arch ${TARGETARCH}"
    fi

    INSTALLER=cmake-${CMAKE_VERSION}-linux-${SUFFIX}.sh

    wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${INSTALLER}

    mkdir -p /opt/cmake-${CMAKE_VERSION}

    sh ${INSTALLER} --skip-license --prefix=/opt/cmake-${CMAKE_VERSION}/

    rm ${INSTALLER}
EOF

ENV PATH=/opt/cmake-${CMAKE_VERSION}/bin:${PATH}

# Compile Doxygen.
FROM requirements AS doxygen-compile

ARG DOXYGEN_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --clean --update --packages flex bison

    git clone --depth=1 --branch Release_$(echo ${DOXYGEN_VERSION} | tr . _) https://github.com/doxygen/doxygen doxygen

    cd doxygen

    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/doxygen-${DOXYGEN_VERSION}

    cmake --build build -j4 --target install
EOF

# Compile Google Test.
FROM requirements AS google-test-compile

ARG GOOGLETEST_VERSION

RUN <<EOF
    set -ex

    git clone --depth=1 --branch=v${GOOGLETEST_VERSION} https://github.com/google/googletest googletest

    cd googletest

    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/google-test-${GOOGLETEST_VERSION}

    cmake --build build -j4

    cmake --build build --target install
EOF

# Compile Kokkos.
FROM requirements AS kokkos-compile

ARG KOKKOS_ARCH
ARG KOKKOS_PRESET
ARG KOKKOS_VERSION

RUN --mount=target=/cmake/presets/kokkos.json,type=bind,source=cmake/presets/kokkos.json <<EOF
    set -ex

    git clone --depth=1 --branch=${KOKKOS_VERSION} https://github.com/kokkos/kokkos kokkos

    cd kokkos

    cp /cmake/presets/kokkos.json CMakePresets.json

    if [ ! -z "${KOKKOS_ARCH}" ];then
        KOKKOS_ARCH_ARG="-DKokkos_ARCH_${KOKKOS_ARCH}:BOOL=ON"
    else
        KOKKOS_ARCH_ARG=""
    fi

    cmake -S . --preset=${KOKKOS_PRESET} \
        -DCMAKE_INSTALL_PREFIX=/opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET} \
        ${KOKKOS_ARCH_ARG}

    cmake --build --preset=${KOKKOS_PRESET} -j4

    cmake --build --preset=${KOKKOS_PRESET} --target=install
EOF

# Build the final image from previous stages.
FROM requirements AS final

ARG DOXYGEN_VERSION
ARG GOOGLETEST_VERSION
ARG KOKKOS_VERSION
ARG KOKKOS_PRESET

COPY --from=doxygen-compile     /opt/doxygen-${DOXYGEN_VERSION}                /opt/doxygen-${DOXYGEN_VERSION}
COPY --from=google-test-compile /opt/google-test-${GOOGLETEST_VERSION}         /opt/google-test-${GOOGLETEST_VERSION}
COPY --from=kokkos-compile      /opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET} /opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET}

ENV Doxygen_ROOT=/opt/doxygen-${DOXYGEN_VERSION}
ENV GTest_ROOT=/opt/google-test-${GOOGLETEST_VERSION}
ENV Kokkos_ROOT=/opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET}
